GET http://localhost:3333/medical/schedulings
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1MDQ0OSIsIm5hbWUiOiJBbmEgQmVhdHJpeiIsInJvbGUiOiJvcGVyYXRvciIsImlhdCI6MTc0OTIxNTA5MywiZXhwIjoxNzQ5MjE1OTkzfQ.JkjPoYY3le9ZH-MPvQaP-_kktQkrDLAepG3mKK3WOjMNjQl6AllK4TTgyoBR1FgQveiX3mBGfiP_iTlnAmx4pwYqQJ6sxh_Uo-2ySzgm1_1bvEnpyP_m0Hl2G9Y3auUI-r_UJjEkK722wOvQdzaXxgbTbrLWCbD4hoVPJ_Z8fd4_BV4DlyuCPGuFwkHu4nB_6VG9404YYDImHkuO-EpHkYQ6qNAieqg4fTw8el7WOKUMRYGVFFT0OSEBsTX700Gjl7TtlbX2cM0q8rWlX8cb_b-bD1YYV1Cykn2Ex7pZf4wjAgwREtPUEzCfpJVBfkZdsD91H_Ua-lU3QEnywX8jsw

###

POST http://localhost:3333/auth/login/operator
Content-Type: application/json

{
  "username": "ana.beatriz",
  "password": "12345678"
}

###

POST http://localhost:3333/auth/login/operator
Content-Type: application/json

{
  "username": "breno.castro",
  "password": "@12Bagaiaro"
}

###

GET http://localhost:3333/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ODcwMCIsImlhdCI6MTc0NzIyNTcwOCwiZXhwIjoxNzQ3ODMwNTA4fQ.crI_YJijGLjSTkrIY4tN5iLjUQgzWto-NCiPJhaI8P2R9-zvx4wPdSgRyzkF-OkDAk0scTvqcq-dpQIhohHK7Qaigg1D9GlzEObePCPXldzJNN6KVbqHojDmsEbKxg_ROUITDUrZjsYyiPdr2N-ol5G2mFLisNHH4CuPe2jQAvikmrf91sVZJ79TLwwR_erztsNSlAt5vtz5lSZ-vNzR83RgLALM1XAQVz4i_litoO0-MGYTMvbcWvI3-nlbv69u0iQcS9rKy_vu2IRbB1rHXJ5FuAD8Ry2PXgjtAr_TsSDktdha9FL7tPXATWHVRXQdqv6pMJWEyq7eToONuwsrZQ

###

POST http://localhost:3333/auth/recover-password
Content-Type: application/json

{
  "email": "breno.castro@deovita.com.br"
}
###

POST http://localhost:3333/auth/reset-password
Content-Type: application/json

{
  "email": "breno.castro@deovita.com.br",
  "code": "UJLHKY",
  "password": "@12Bagaiaro"
}
