@authtoken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NTg1MSIsIm5hbWUiOiJTaGFybGVzIFJlaW5hbSIsInJvbGUiOiJtZWRpY2FsIiwic2Vzc2lvbklkIjoiY2UwMzU5OTQtNzQwYS00OGNhLThkZjItNTMzMjEzYzNmZmQ2IiwiaWF0IjoxNzU0NDkwMjY5LCJleHAiOjE3NTQ0OTExNjl9.UJKASwkjecYCbqVG9VmlJGURA4bz2KMQKFsJjdZUGdlhsqp7-PdoE0NNMtV4DzzBL6flUWBei2EPGSte6o8gYlx_jXC4af8hCUBQe9fTsTbVwrteXebBlM7cQjc5THPEzJKmG-uXSXAJ04vBek_4KsSr3tKr15ynyAy13xnJw8ZDe1ZSV3sLkudSOFWJQI44ACda_jS5dtx2f3-pkxKywnHHRm9MJxMTsSkt_U0HmZZz1h9-O9jqZEbmZ2nNAsR84dKol1cn4BnvQxqFooYbbg3XQBdHr8vvu54LzOsxJt4K5uRtuaWAzPWCcAnsqiznBwIIjYmir6bnbglKoBWZrg

@authtokenrefresh = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NTg1MSIsIm5hbWUiOiJTaGFybGVzIFJlaW5hbSIsInJvbGUiOiJtZWRpY2FsIiwiaWF0IjoxNzU0NDkwMjY5LCJleHAiOjE3NTUwOTUwNjl9.JZ3WXH3zTAIDm_L07koURveoG-bGncdSB3dK11aOXpoGI7VDdBNbkmyvnSV5zRSPi0yMp9gprUoncEA0liXnlAVIYpMzPJMjDHldxojV6QCXK8ca22xGeXkuZWV9y98YVtaLl0V1o1Mj5dzWh8-AnWugcY4vVyJc2jAaiLPAI3ks_z96akkRukVz94wTf01cSaeXGeoJgZrmNY0_WkFB78qEUbIRooIYzuhPIfH6OYC9JExVGAHbkhGfZEhnZ_ufKc04AbLZr3t-fEeK6V-_DUW4aJeENbTJNxRsAmXZe1If4fpB14ZV74gws2BR3J1h6ZMNWslBPhGz77HGlDs7RA

@authtokenpatient = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NjIxMTAiLCJuYW1lIjoiU2hlaWxhIE1hcmlhIiwicm9sZSI6InBhdGllbnQiLCJpYXQiOjE3NTQzNDc2MjksImV4cCI6MTc1NDk1MjQyOX0.ThcvDjbmc_NG9pQ0Rxxw0WbYDHNhNLxHsTaD7GTjSYDqPCaTkIt6pGMZ--NmYPUBYcPnjn8Y4-ROvvmtfoSR8VpmgPAteojZDyPZcTWsNGBrxHJsJetP-aqn73KmxdmwlcONeJZkqO8Zn1uu6dRIdd7ZWp-elKUTFgb8frNqH-y4EphuLm7o0e9qucoBCFEQZ94CqWcyP13hTVZrjcZkz1qNfpaGTQ5XeH3HObEoocpmaZgBdMWWQYsHzFVSa_yyw_vAdoPykjRtok-neGpnu87MzQjgqhLzySDOG7CeCpgfCq6fMHf4uwILKDUKMxMzc8NI7niwkq06NzrxS5dYzg

###

GET http://localhost:3333/medical/schedulings
Authorization: Bearer {{authtoken}}

###

POST http://localhost:3333/auth/login
Content-Type: application/json

{
  "type": "medical",
  "access": "7845-CE",
  "password": "@12Bagaiaro"
}

###

POST http://localhost:3333/auth/me/refresh-token
Cookie: refresh_token={{authtokenrefresh}}

###

POST http://localhost:3333/auth/recover-password
Content-Type: application/json

{
  "email": "breno.castro@deovita.com.br"
}

###

POST http://localhost:3333/auth/reset-password
Content-Type: application/json

{
  "email": "breno.castro@deovita.com.br",
  "code": "UJLHKY",
  "password": "@12Bagaiaro"
}

###
POST http://localhost:3333/auth/login
Content-Type: application/json

{
  "type": "patient",
  "access": "84981725353",
  "password": "b91890f1"
}

###

POST http://localhost:3333/auth/login
Content-Type: application/json

{
  "type": "medical",
  "access": "7845-CE",
  "password": "123"
}

###

GET http://localhost:3333/patient/me/exams?page=1
Authorization: Bearer {{authtoken}}

###

GET http://localhost:3333/health

###

GET http://localhost:3333/assessment/1089155
Authorization: Bearer {{authtoken}}

###

GET http://localhost:3333/medical/me/schedulings/daily?date=2025-07-09
Authorization: Bearer {{authtoken}}

###

POST http://localhost:3333/attendance/start
Content-Type: application/json
Authorization: Bearer {{authtoken}}

{
  "attendance_id": 1090368
}

###

GET http://localhost:3333/attendance
Authorization: Bearer {{authtoken}}

###

GET http://localhost:3333/auth/requirements
Authorization: Bearer {{authtoken}}

###

GET http://localhost:3333/auth/sessions/ad8257dd-971d-45a4-9bba-75a4615566cd/invalidate
