@authtoken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1MDQ0OSIsIm5hbWUiOiJBbmEgQmVhdHJpeiIsInJvbGUiOiJvcGVyYXRvciIsImlhdCI6MTc1MzE4NjI1MSwiZXhwIjoxNzUzNzkxMDUxfQ.hF4z1smg4jFofT1NwzaLLgRhQS7D4yzysRfPgU-v0ddiKLuNBW57DfBn4f7xrT5bespGEEiV0TNvKeEBHKJytOCQHHwS9nW1lBadvrsh6PCWGgbqxD9HFDAfXroeGa35WvE-PpLZFdi28gaLl5ZesQWE_JR475cx51cxHQ9Brclr4v1pGe74_nzLip4bA1Lyrz2oNUJEg9ow71ZfHXtsRgVOeijKvKK3nKht2alAmsep9SLGz_RoTNQ2hbPzPI8U8AHFqFmV1UdcrbHlvIekpF8gUZnpJ2FVEVQzysGoHfDDf0YwZTOn6FCrKHbW0I142ebQX99nf0r9ER43L4KKlQ

GET http://localhost:3333/medical/schedulings
Authorization: Bearer {{authtoken}}

###

POST http://localhost:3333/auth/login
Content-Type: application/json

{
  "type": "operator",
  "access": "ana.beatriz",
  "password": "12345678"
}

###

GET http://localhost:3333/
Authorization: Bearer {{authtoken}}

###

POST http://localhost:3333/auth/recover-password
Content-Type: application/json

{
  "email": "breno.castro@deovita.com.br"
}
###

POST http://localhost:3333/auth/reset-password
Content-Type: application/json

{
  "email": "breno.castro@deovita.com.br",
  "code": "UJLHKY",
  "password": "@12Bagaiaro"
}

###

POST http://localhost:3333/auth/login/patient
Content-Type: application/json

{
  "cpf": "84981725353",
  "password": "b91890f1"
}

###

GET http://localhost:3333/patient/exams
Authorization: Bearer {{authtoken}}
